<?xml version="1.0"?>

<robot name="hector_erratic"
     xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
   xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
   xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
   xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

    <!-- Included URDF Files -->
    <xacro:include filename="$(find erratic_description)/urdf/erratic_base.xacro" />
<!--    <xacro:include filename="$(find hector_sensors_description)/urdf/hokuyo_utm30lx.urdf.xacro" />-->
    
    <erratic />

    <!-- BASE LASER ATTACHMENT -->
<!--    <erratic_hokuyo_laser parent="base_top_link">
        <origin xyz="${top_size_x/2 - 0.01 - 0.04} 0 ${top_size_z/2}" rpy="0 0 0" />
    </erratic_hokuyo_laser>
    -->
      <xacro:include filename="$(find hector_sensors_description)/urdf/hokuyo_utm30lx.urdf.xacro" />
  <xacro:hokuyo_utm30lx name="laser1" parent="base_top_link" ros_topic="base_scan/scan" update_rate="40" ray_count="1081" min_angle="135" max_angle="-135">
    <origin xyz="${top_size_x/2 - 0.01 - 0.04} 0 ${top_size_z/2 +0.1}" rpy="0 0 0"/>
  </xacro:hokuyo_utm30lx>
</robot>
